export const TYPE = {
    SET_SEARCH_LIST: 'SET_SEARCH_LIST',
    SET_SEARCH_INIT: 'SET_SEARCH_INIT',
    SET_ADDRESS_ZOOM: 'SET_ADDRESS_ZOOM',
    SLIDE_MODAL_OPEN: 'SLIDE_MODAL_OPEN',
    SLIDE_MODAL_CLOSE: 'SLIDE_MODAL_CLOSE',
    POPUP_MODAL_OPEN: 'POPUP_MODAL_OPEN',
    POPUP_MODAL_CLOSE: 'POPUP_MODAL_CLOSE',
    SET_INDEX: 'SET_INDEX',
    SET_MARKER: 'SET_MAKER',
    SET_SEARCH_MARKER: 'SET_SEARCH_MARKER',
    SET_PLACE_DETAIL: 'SET_PLACE_DETAIL',
    SET_IMAGE: 'SET_IMAGE',
};
