export const TYPE = {
    SET_SEARCH_LIST: 'SET_SEARCH_LIST',
    SET_ADDRESS_ZOOM: 'SET_ADDRESS_ZOOM',
    SLIDE_MODAL_OPEN: 'SLIDE_MODAL_OPEN',
    SLIDE_MODAL_CLOSE: 'SLIDE_MODAL_CLOSE',
    SET_INDEX: 'SET_INDEX',
}